version: '3.3'
services:
    web:
        build:
            context: .
        command: npm start
        ports:
            - '${PORT}:${PORT}'
        environment:
            NODE_ENV: development
            PORT: ${PORT}
